name: Publish Python 🐍 distribution 📦 to PyPI

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # required for trusted publishing (optional)
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade build

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
